# Generated by Django 5.2.5 on 2025-10-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceApp', '0003_invoice_stripe_checkout_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='kind',
            field=models.CharField(choices=[('ONE_OFF', 'One-off'), ('DEPOSIT', 'Deposit'), ('BALANCE', 'Balance'), ('RECURRING', 'Recurring')], default='ONE_OFF', max_length=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='period_end',
            field=models.DateField(blank=True, help_text='For recurring: service period end', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='period_start',
            field=models.DateField(blank=True, help_text='For recurring: service period start', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='recurring_code',
            field=models.SlugField(blank=True, help_text='e.g. hosting, domain, maintenance', max_length=40),
        ),
    ]
