# Generated by Django 5.2.5 on 2025-10-23 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0004_project_priority_project_show_priority_to_client_and_more'),
        ('proposalApp', '0019_proposalaccountinvite'),
        ('timeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activetimer',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_timers', to='projectApp.projecttask'),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='projectApp.projecttask'),
        ),
        migrations.AlterField(
            model_name='activetimer',
            name='job_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='proposalApp.jobrate'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='job_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to='proposalApp.jobrate'),
        ),
    ]
