# Generated by Django 5.2.5 on 2025-11-19 21:34

import companyApp.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('primary_contact_name', models.CharField(blank=True, max_length=120)),
                ('primary_contact_email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address_line1', models.CharField(blank=True, max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('state_region', models.CharField(blank=True, max_length=120)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, default='USA', max_length=120)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, help_text='PNG/JPEG/WebP, up to 3MB.', null=True, upload_to=companyApp.models.logo_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), companyApp.models.validate_logo_size])),
                ('logo_external_url', models.URLField(blank=True, help_text='Optional external logo URL (e.g., Google Drive shared link).')),
                ('consultation_sheet_url', models.URLField(blank=True, help_text='Link to internal consultation / project sheet (BeeDev-only).')),
                ('status', models.CharField(choices=[('PROSPECT', 'Prospect'), ('CONVERTED_PROSPECT', 'Converted Prospect'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=24)),
                ('pipeline_status', models.CharField(blank=True, choices=[('NEW', 'New'), ('HOLDING', 'Holding'), ('IN_PROGRESS', 'In Progress'), ('ONGOING', 'On Going'), ('FINISHED', 'Finished'), ('INACTIVE', 'Inactive')], default='NEW', max_length=24)),
                ('work_status', models.CharField(choices=[('NONE', 'Not Started'), ('DISCOVERY', 'Discovery / Intake'), ('PROPOSAL_SENT', 'Proposal Sent'), ('PROPOSAL_APPROVED', 'Proposal Approved'), ('ROAD_MAP_SENT', 'Road Map Sent'), ('DEPOSIT_INVOICE_SENT', 'Deposit Invoice Sent'), ('DEPOSIT_PAID', 'Deposit Paid'), ('PROJECT_SCHEDULED', 'Project Scheduled'), ('DESIGN_STARTED', 'Design Started'), ('DESIGN_APPROVED', 'Design Approved'), ('DEVELOPMENT_STARTED', 'Development Started'), ('QA_REVIEW', 'QA / Review'), ('DEVELOPMENT_APPROVED', 'Development Approved'), ('READY_FOR_LAUNCH', 'Ready for Launch'), ('LIVE', 'Site Live'), ('FINAL_INVOICE_SENT', 'Final Invoice Sent'), ('FINAL_INVOICE_PAID', 'Final Invoice Paid'), ('RECURRING_INVOICE_SENT', 'Recurring Invoice Sent'), ('RECURRING_INVOICE_PAID', 'Recurring Invoice Paid'), ('ON_HOLD', 'On Hold')], default='NONE', help_text='Micro status for current work state (e.g., design started, deposit invoice sent).', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CompanyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Short label, e.g. 'Staging Site' or 'Instagram'.", max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('visible_to_client', models.BooleanField(default=True, help_text='If unchecked, only staff sees this link in the portal.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['link_type__sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CompanyLinkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text="Internal key (e.g. 'preview', 'social', 'assets_folder').", unique=True)),
                ('label', models.CharField(help_text="Human label shown in the UI, e.g. 'Preview Link'.", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=100, help_text='Lower numbers appear first.')),
                ('is_system', models.BooleanField(default=False, help_text='Protect system types from accidental deletion.')),
            ],
            options={
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='CompanyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_type', models.CharField(choices=[('CLIENT', 'Client Contact'), ('STAFF', 'Staff')], default='CLIENT', max_length=10)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary point of contact for this company.')),
                ('is_active', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortalInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('visible_to_client', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProposalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='proposals/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, help_text='Optional roadmap PDF or document.', null=True, upload_to='roadmaps/')),
                ('notes', models.TextField(blank=True, help_text='Optional text roadmap / milestones.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('CSA', 'Client Services Agreement'), ('SOW', 'Statement of Work'), ('NDA', 'Non-Disclosure Agreement'), ('OTHER', 'Other')], default='SOW', max_length=12)),
                ('title', models.CharField(blank=True, help_text="Optional friendly title (e.g., 'Website Rebuild SOW').", max_length=255)),
                ('file_signed', models.FileField(help_text='Final signed PDF (downloaded from BoldSign or other provider).', upload_to='agreements/signed/')),
                ('file_source', models.FileField(blank=True, help_text='(Optional) original doc or unsigned PDF.', null=True, upload_to='agreements/source/')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent for Signature'), ('SIGNED', 'Fully Signed'), ('SUPERSEDED', 'Superseded'), ('TERMINATED', 'Terminated')], default='SIGNED', max_length=12)),
                ('version', models.PositiveIntegerField(default=1)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('signed_by_name', models.CharField(blank=True, max_length=120)),
                ('signed_by_email', models.EmailField(blank=True, max_length=254)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('countersigned_by', models.CharField(blank=True, max_length=120)),
                ('countersigned_at', models.DateTimeField(blank=True, null=True)),
                ('esign_provider', models.CharField(blank=True, help_text="e.g., 'BoldSign', 'DocuSign', etc.", max_length=60)),
                ('esign_envelope_id', models.CharField(blank=True, help_text='Provider-specific ID (e.g., BoldSign document ID).', max_length=120)),
                ('esign_view_url', models.URLField(blank=True, help_text="Link to the provider's hosted document/view.")),
                ('visible_to_client', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='companyApp.agreement')),
            ],
            options={
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
    ]
