# Generated by Django 5.2.5 on 2025-11-19 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companyApp', '0001_initial'),
        ('prospectApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreements_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='prospect',
            field=models.OneToOneField(blank=True, help_text='Original prospect record, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company', to='prospectApp.prospect'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='companyApp.company'),
        ),
        migrations.AddField(
            model_name='companylink',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='companyApp.company'),
        ),
        migrations.AddField(
            model_name='companylink',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_links_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companylink',
            name='link_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='links', to='companyApp.companylinktype'),
        ),
        migrations.AddField(
            model_name='companymember',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='companyApp.company'),
        ),
        migrations.AddField(
            model_name='companymember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='companies', through='companyApp.CompanyMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='portalinvite',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='companyApp.company'),
        ),
        migrations.AddField(
            model_name='portalinvite',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_invites_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='portalinvite',
            name='prospect',
            field=models.ForeignKey(blank=True, help_text='Original prospect record, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_invites', to='prospectApp.prospect'),
        ),
        migrations.AddField(
            model_name='projectupdate',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='companyApp.company'),
        ),
        migrations.AddField(
            model_name='projectupdate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposaldocument',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_document', to='companyApp.company'),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap', to='companyApp.company'),
        ),
        migrations.AddIndex(
            model_name='agreement',
            index=models.Index(fields=['company', 'status'], name='companyApp__company_3d786d_idx'),
        ),
        migrations.AddIndex(
            model_name='agreement',
            index=models.Index(fields=['company', 'kind'], name='companyApp__company_437027_idx'),
        ),
        migrations.AddIndex(
            model_name='companylink',
            index=models.Index(fields=['company', 'visible_to_client', 'is_active'], name='companyApp__company_c248bd_idx'),
        ),
        migrations.AddIndex(
            model_name='companymember',
            index=models.Index(fields=['company', 'user', 'is_active'], name='companyApp__company_e012b2_idx'),
        ),
        migrations.AddIndex(
            model_name='companymember',
            index=models.Index(fields=['company', 'member_type'], name='companyApp__company_7310f5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='companymember',
            unique_together={('company', 'user')},
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['name'], name='companyApp__name_a038b8_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['slug'], name='companyApp__slug_52ac3a_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['status'], name='companyApp__status_cbffb7_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['pipeline_status'], name='companyApp__pipelin_03b7db_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['work_status'], name='companyApp__work_st_0152e2_idx'),
        ),
    ]
