# Generated by Django 5.2.5 on 2025-12-09 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyApp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='pipeline_status',
            field=models.CharField(blank=True, choices=[('NEW', 'New'), ('HOLDING', 'Holding'), ('IN_PROGRESS', 'In Progress'), ('ONGOING', 'On Going'), ('FINISHED', 'Finished'), ('INACTIVE', 'Inactive'), ('LOST', 'Lost')], default='NEW', max_length=24),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('PROSPECT', 'Prospect'), ('CONVERTED_PROSPECT', 'Converted Prospect'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('LOST', 'Lost')], default='ACTIVE', max_length=24),
        ),
    ]
