# Generated by Django 5.2.5 on 2025-12-17 17:43

import companyApp.uploads
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyApp', '0003_alter_company_pipeline_status_alter_company_status'),
        ('prospectApp', '0003_alter_prospect_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('visible_to_client', models.BooleanField(default=True)),
                ('pinned', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=companyApp.uploads.invoices_upload_to)),
                ('external_url', models.URLField(blank=True)),
                ('visible_to_client', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-paid_at', '-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='projectupdate',
            name='company',
        ),
        migrations.RemoveField(
            model_name='projectupdate',
            name='created_by',
        ),
        migrations.AlterModelOptions(
            name='proposaldocument',
            options={'ordering': ['-is_active', '-version', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='roadmap',
            options={'ordering': ['-is_active', '-version', '-created_at']},
        ),
        migrations.RenameField(
            model_name='proposaldocument',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='notes',
        ),
        migrations.AddField(
            model_name='company',
            name='project_phase',
            field=models.CharField(choices=[('NONE', 'Not Started'), ('DISCOVERY', 'Discovery'), ('DESIGN', 'Design'), ('DEVELOPMENT', 'Development'), ('TESTING', 'Testing / QA'), ('LAUNCH', 'Launch'), ('MAINTENANCE', 'Maintenance')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='project_phase_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposaldocument',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposaldocument',
            name='external_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='proposaldocument',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proposaldocument',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='proposaldocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='proposaldocument',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='proposaldocument',
            name='visible_to_client',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roadmap',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roadmaps_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='external_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='visible_to_client',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='file_signed',
            field=models.FileField(help_text='Final signed PDF (downloaded from BoldSign or other provider).', upload_to=companyApp.uploads.agreements_signed_upload_to),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='file_source',
            field=models.FileField(blank=True, help_text='(Optional) original doc or unsigned PDF.', null=True, upload_to=companyApp.uploads.agreements_source_upload_to),
        ),
        migrations.AlterField(
            model_name='proposaldocument',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='companyApp.company'),
        ),
        migrations.AlterField(
            model_name='proposaldocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=companyApp.uploads.proposals_upload_to),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to='companyApp.company'),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=companyApp.uploads.roadmaps_upload_to),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['project_phase'], name='companyApp__project_7089c2_idx'),
        ),
        migrations.AddIndex(
            model_name='proposaldocument',
            index=models.Index(fields=['company', 'is_active'], name='companyApp__company_841d3d_idx'),
        ),
        migrations.AddIndex(
            model_name='proposaldocument',
            index=models.Index(fields=['company', 'visible_to_client'], name='companyApp__company_8f7a3f_idx'),
        ),
        migrations.AddIndex(
            model_name='roadmap',
            index=models.Index(fields=['company', 'is_active'], name='companyApp__company_e276b6_idx'),
        ),
        migrations.AddIndex(
            model_name='roadmap',
            index=models.Index(fields=['company', 'visible_to_client'], name='companyApp__company_e76be3_idx'),
        ),
        migrations.AddConstraint(
            model_name='proposaldocument',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('company',), name='one_active_proposal_per_company'),
        ),
        migrations.AddConstraint(
            model_name='roadmap',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('company',), name='one_active_roadmap_per_company'),
        ),
        migrations.AddField(
            model_name='companyupdatelog',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='companyApp.company'),
        ),
        migrations.AddField(
            model_name='companyupdatelog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='companyApp.company'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ProjectUpdate',
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['company', 'visible_to_client'], name='companyApp__company_0482c1_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['company', 'paid_at'], name='companyApp__company_840b91_idx'),
        ),
    ]
