# Generated by Django 5.2.5 on 2025-10-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyApp', '0003_dncreason_dncentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('PROSPECT', 'Prospect'), ('CONVERTED_PROSPECT', 'Converted Prospect'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='CONVERTED_PROSPECT', max_length=20),
        ),
    ]
