# Generated by Django 5.2.5 on 2025-10-23 17:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoiceApp', '0003_invoice_stripe_checkout_session_id_and_more'),
        ('projectApp', '0004_project_priority_project_show_priority_to_client_and_more'),
        ('proposalApp', '0019_proposalaccountinvite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=240)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proposalApp.jobrate')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApp.project')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_timer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('period', models.CharField(choices=[('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Bi-Weekly'), ('SEMI', 'Semi-Monthly'), ('MONTHLY', 'Monthly'), ('CUSTOM', 'Custom')], default='BIWEEKLY', max_length=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_finalized', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-start_date', 'id'),
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=240)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('duration_secs', models.PositiveIntegerField(default=0)),
                ('billable', models.BooleanField(default=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_approved', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='invoiceApp.invoice')),
                ('job_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to='proposalApp.jobrate')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_locked', to=settings.AUTH_USER_MODEL)),
                ('payroll_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='timeApp.payrollbatch')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='projectApp.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-start_at', 'id'),
                'indexes': [models.Index(fields=['project', 'user', 'start_at'], name='timeApp_tim_project_96c399_idx'), models.Index(fields=['approved_at'], name='timeApp_tim_approve_0d2fbe_idx'), models.Index(fields=['invoice'], name='timeApp_tim_invoice_3cf81b_idx')],
            },
        ),
    ]
