# Generated by Django 5.2.5 on 2025-11-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(blank=True, max_length=120)),
                ('company_name', models.CharField(blank=True, max_length=160)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('address1', models.CharField(blank=True, max_length=160)),
                ('address2', models.CharField(blank=True, max_length=160)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('state', models.CharField(blank=True, max_length=80)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, default='USA', max_length=60)),
                ('website_url', models.URLField(blank=True, help_text='Leave blank if no site.', max_length=300)),
                ('sheet_url', models.URLField(blank=True, help_text='Link to external sheet/record for this prospect (e.g. consult form).', max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('QUALIFIED', 'Qualified'), ('CONSULT_PENDING', 'Consultation Pending'), ('CONSULT_COMPLETE', 'Consultation Complete'), ('PROPOSAL_SENT', 'Proposal Sent'), ('WON', 'Won'), ('CLOSED_LOST', 'Closed / Lost')], default='NEW', max_length=32)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags (optional).', max_length=200)),
                ('last_contacted_at', models.DateTimeField(blank=True, null=True)),
                ('next_follow_up_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProspectNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=160)),
                ('body_md', models.TextField(blank=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-is_pinned', '-created_at', 'pk'),
            },
        ),
    ]
