# Generated by Django 5.2.5 on 2025-11-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospectApp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('CONSULT_PENDING', 'Consultation Pending'), ('CONSULT_COMPLETE', 'Consultation Complete'), ('PROPOSAL_SENT', 'Proposal Sent'), ('WON', 'Won'), ('LST', 'Closed / Lost')], default='NEW', max_length=32),
        ),
    ]
