# Generated by Django 5.2.5 on 2025-10-02 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyApp', '0004_alter_company_status'),
        ('prospectApp', '0003_prospectnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospects', to='companyApp.company'),
        ),
    ]
