# Generated by Django 5.2.5 on 2025-11-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('STAFF', 'Staff'), ('CLIENT', 'Client')], default='CLIENT', max_length=20),
        ),
    ]
