# Generated by Django 5.2.5 on 2025-11-24 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companyApp', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingTaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(help_text="Short code, e.g. 'staff-welcome-email'.", max_length=80, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('audience', models.CharField(choices=[('STAFF', 'Staff'), ('CLIENT', 'Client')], help_text='Whether this task is used for staff or client onboarding.', max_length=12)),
                ('default_order', models.PositiveIntegerField(default=100, help_text='Smaller numbers appear earlier in the checklist.')),
                ('is_active', models.BooleanField(default=True, help_text="Inactive templates won't be added to new onboarding lists.")),
            ],
            options={
                'ordering': ('audience', 'default_order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='OnboardingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('STAFF', 'Staff Onboarding'), ('CLIENT', 'Client Onboarding')], max_length=12)),
                ('title', models.CharField(help_text="Friendly label, e.g. 'Staff Onboarding – Jane Doe'.", max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('visible_to_subject', models.BooleanField(default=False, help_text='If true: staff_user/client will see this checklist in their portal.')),
                ('management_only', models.BooleanField(default=False, help_text='If true: only management-level staff should see in UI.')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Optional: when the ENTIRE list was completed.', null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, help_text='Set for client onboarding.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_onboarding_lists', to='companyApp.company')),
                ('created_for', models.ForeignKey(blank=True, help_text='Who created this list (usually a manager/owner).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_lists_created', to=settings.AUTH_USER_MODEL)),
                ('staff_user', models.ForeignKey(blank=True, help_text='Set for staff/intern onboarding.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_onboarding_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='OnboardingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('resource_url', models.URLField(blank=True, help_text='Optional link relevant to this task (contract, preview site, folder, etc.).')),
                ('notes', models.TextField(blank=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_items_completed', to=settings.AUTH_USER_MODEL)),
                ('onboarding_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='onboardingApp.onboardinglist')),
                ('template', models.ForeignKey(blank=True, help_text='Optional link back to the template this was created from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_items', to='onboardingApp.onboardingtasktemplate')),
            ],
            options={
                'ordering': ('sort_order', 'pk'),
            },
        ),
    ]
