# Generated by Django 5.2.5 on 2025-12-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboardingApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboardinglistitem',
            name='resource_url',
        ),
        migrations.AddField(
            model_name='onboardinglistitem',
            name='requires_resource',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onboardinglistitem',
            name='resource_added',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onboardingtasktemplate',
            name='requires_resource',
            field=models.BooleanField(default=False),
        ),
    ]
