# Generated by Django 5.2.5 on 2025-10-06 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposalApp', '0010_draftnote_proposalsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=160)),
                ('body_md', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_visible_to_client', models.BooleanField(default=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='proposalApp.proposal')),
            ],
            options={
                'ordering': ('sort_order', 'pk'),
            },
        ),
    ]
