# Generated by Django 5.2.5 on 2025-10-08 16:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposalApp', '0012_proposalsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='snap_total_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='proposaldraft',
            name='total_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='proposallineitem',
            name='line_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
