# Generated by Django 5.2.5 on 2025-10-08 17:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposalApp', '0013_proposal_snap_total_hours_proposaldraft_total_hours_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='snap_total_hours',
            new_name='hours_subtotal',
        ),
        migrations.AddField(
            model_name='proposal',
            name='hours_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
