# Generated by Django 5.2.5 on 2025-10-13 14:41

import django.db.models.deletion
import proposalApp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposalApp', '0014_rename_snap_total_hours_proposal_hours_subtotal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='requires_verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposal',
            name='discount_requires_verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposal',
            name='is_discount_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposal',
            name='verification_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='verification_checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals_verified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposal',
            name='verification_file',
            field=models.FileField(blank=True, null=True, upload_to=proposalApp.models.proof_upload_to),
        ),
        migrations.AddField(
            model_name='proposal',
            name='verification_note',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='proposalapplieddiscount',
            name='pending_verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposalapplieddiscount',
            name='requires_verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposaldraft',
            name='discount_requires_verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposaldraft',
            name='is_discount_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposaldraft',
            name='verification_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposaldraft',
            name='verification_checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_drafts_verified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposaldraft',
            name='verification_file',
            field=models.FileField(blank=True, null=True, upload_to=proposalApp.models.proof_upload_to),
        ),
        migrations.AddField(
            model_name='proposaldraft',
            name='verification_note',
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
