# Generated by Django 5.2.5 on 2025-10-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposalApp', '0015_discount_requires_verification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='stackable',
            field=models.BooleanField(default=False),
        ),
    ]
