# Generated by Django 5.2.5 on 2025-10-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposalApp', '0008_proposal_contact_email_proposal_contact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposaldraft',
            name='addons_md',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposaldraft',
            name='included_md',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposaldraft',
            name='legal_terms_md',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposaldraft',
            name='maintenance_md',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposaldraft',
            name='overview_md',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposaldraft',
            name='payment_terms_md',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposaldraft',
            name='summary_md',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposaldraft',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
