# Generated by Django 5.2.5 on 2025-10-01 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposalApp', '0009_proposaldraft_addons_md_proposaldraft_included_md_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('subject', models.CharField(max_length=160)),
                ('body_md', models.TextField(blank=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='proposalApp.proposaldraft')),
            ],
            options={
                'ordering': ('sort_order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='ProposalSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('subject', models.CharField(max_length=160)),
                ('body_md', models.TextField(blank=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='proposalApp.proposal')),
            ],
            options={
                'ordering': ('sort_order', 'pk'),
            },
        ),
    ]
