# Generated by Django 5.2.5 on 2025-10-06 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposalApp', '0011_proposalnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_md', models.TextField(blank=True)),
                ('is_visible_to_client', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='proposalApp.proposal')),
            ],
        ),
    ]
